version: '5.0'

actions:
  generate_dataset:
    run: > 
      ehrql:v1 generate-dataset 
      analysis/dataset_definition.py
      --test-data-file analysis/test_prom_dataset.py
      --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
  
  generate_measures:
    run: >
      ehrql:v1 generate-measures
      analysis/measures_definition.py
      --output output/measures.csv
    outputs:
      highly_sensitive:
        dataset: output/measures.csv